### ISSUE TITLE
Don't load all list of Eligible OU's

### ISSUE THREAD

**Issue by dimarev-ma** [aws-samples/iam-identity-center-team#58] opened 2023-08-16 08:58 UTC
**Describe the bug**
When you have lot of OU's the application don't load the full list of OU's

**To Reproduce**
1. Go to Eligibility policy
2. Click on OU's
3. Scroll down
4. You will not see all the OU's (if you have more then 5)

**Expected behavior**
See all OU list

**Desktop (please complete the following information):**
 - OS: osx 13.5
 - Browser chrome
 - Version 115.0.5790.170

**Additional context**
On aws accounts need to click load more to see all existing OU's look like this is what missing

**Comment by tomerr-ma** [comment] 2023-08-20 07:20
Not sure how it works for you, but if I understand it right, the problem relies here - https://github.com/aws-samples/iam-identity-center-team/blob/dev/amplify/backend/function/teamgetOUs/src/index.py where the getOUs function is missing pagination and getting values of more than one page (the API returns the first 5 OUs in my case).

**Comment by lvthillo** [comment] 2023-08-21 09:07
I think it works on my side because we don't have more than 5 OUs per "nested" OU.

**Comment by lvthillo** [comment] 2023-08-21 10:48
@tomerr-ma  There is indeed no pagination, than can be improved, but for me it lists more than 5 ous. So probably enough in my case to list them all (nested ous).

**Comment by tawoyinfa** [comment] 2023-08-28 17:51
@lvthillo thanks for working on this. @tomerr-ma can you confirm that the issue has been fixed by #60

**Comment by andyt10** [comment] 2023-08-29 05:40
@tawoyinfa 
I've just deployed the latest version of TEAM (fc7b6f68) and encountered an issue that causes the UI to crash after a few seconds.

Perhaps brought in by #60, the PR for this Issue.

This is the response to the call that causes the crash

Console: `error fetching OUs`
```
{
    "data": {
        "getOUs": null
    },
    "errors": [
        {
            "path": [
                "getOUs"
            ],
            "data": null,
            "errorType": "Lambda:Unhandled",
            "errorInfo": null,
            "locations": [
                {
                    "line": 2,
                    "column": 3,
                    "sourceName": null
                }
            ],
            "message": "'NoneType' object is not iterable"
        }
    ]
}
```

Lambda logs point to OU pagination:

```
You specified an invalid value for nextToken. You must get the value from the response to a previous call to the API.

[ERROR] TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/var/task/index.py", line 36, in handler
    OUs = listOUs(rootOU[0]['Id'])
  File "/var/task/index.py", line 29, in listOUs
    OUs.extend(getOUs(OU["Id"]))
```

It appears related to OU pagination: https://github.com/aws-samples/iam-identity-center-team/blob/main/amplify/backend/function/teamgetOUs/src/index.py#L19

A call to `list_accounts` is made instead of further `list_organizational_units_for_parent` calls.

I believe this line should instead be:

```
 response = client.list_organizational_units_for_parent(ParentId=id, NextToken=response["NextToken"])
```

Happy to open a PR and fix, unless someone gets to it earlier. Just a bit busy the next couple of days.

It might also be worth adding some tests and test coverage requirements to this Solution.
I am not sure how we'd go about this the right way...I am happy to write some if a suggested method is provided.
I do recognise the additional overhead may put people off or be undesirable, so it's a discussion first of all. 

*As an interesting(?) additional note. The OU that this crashed on didn't actually have additional nested OUs inside, just a lot of accounts. So it seems the NextToken is returned on the `ListOrganizationalUnitsForParent` even if no child OUs are present.*

**Comment by lvthillo** [comment] 2023-08-29 06:13
@andyt10 Yes it should be `list_organizational_units_for_parent` of course, I made that mistake but for some reason (because of my OU/account structure?) it worked on my organization (with the wrong API call). What if you update that line in your lambda and test again?

**Comment by andyt10** [comment] 2023-08-29 06:18
> What if you update that line in your lambda and test again?
I tested locally before replying here, it returned the list of OUs as expected.

I'm not sure why but it didn't occur to me that I could just edit the lambda in the console and test the full app again till your reply 😄 

When I did test this way, the call returned successfully and there were no longer the UI issues.

**Comment by lvthillo** [comment] 2023-08-29 06:37
@andyt10 

For me it wasn't failing because I never need the "`nextToken`" I think. We have 20 OUs or something but they are all in our initial output (without pagination).  I suspect the number of returned OUs in one call might be region-specific. 
Still, your last comment below is not super clear to me:

`As an interesting(?) additional note. The OU that this crashed on didn't actually have additional nested OUs inside, just a lot of accounts. So it seems the NextToken is returned on the ListOrganizationalUnitsForParent even if no child OUs are present.`

Does it still appear with the "fix"?

**Comment by andyt10** [comment] 2023-08-29 07:51
@lvthillo 
> Still, your last comment below is not very clear to me:

Apologies for that.
The comment I made was just saying that the `NextToken` has a value, even if there's no 'next' values to iterate on.

The OU in my AWS Organization that resulted in the error doesn't have any Child OUs, but it reliably always got a NextToken on the `ListOrganizationalUnitsForParent` call whereas others (also without Child OUs) did not. 
The only reason I could think of is it did have a larger number of Accounts inside it (> 30)

> Does it still appear with the "fix"? 
All OUs in the Organization appear in the TEAM API response, from my cross-checking with the console.

I see you've opened an [issue](#67) for this, cheers.

**Comment by andyt10** [comment] 2023-08-30 00:15
Thanks @lvthillo 
I can confirm #67 has resolved the issue, and the OU pagination works. 

As mentioned above, I don't actually have pages of OUs but I do get a NextToken on one specific OU (that has no children) every time and it seems to handle this case as expected.

**Closed** 2023-10-05 12:27 UTC
