### ISSUE TITLE
Blank page when try to get into Eligibility policy

### ISSUE THREAD

**Issue by eladhaz05** [aws-samples/iam-identity-center-team#101] opened 2023-10-18 15:05 UTC
**Describe the bug**
After going thorugh the dpeloymnet process in here https://aws-samples.github.io/iam-identity-center-team/docs/deployment/deployment_process.html i wanted to add eligibility policies. When i go to the page i got blank 

**To Reproduce**
1. Go to Eligibility policy in the Team application
4. See blank page in chrome

**Expected behavior**
See the page 

**Screenshots**
![Screenshot 2023-10-18 at 18 27 07](https://github.com/aws-samples/iam-identity-center-team/assets/29125519/4d4b7fab-27be-4dd8-bfcc-63648af279b2)

[
<img width="919" alt="Screenshot 2023-10-18 at 17 58 33" src="https://github.com/aws-samples/iam-identity-center-team/assets/29125519/ebad7d8b-638f-42f5-a4d5-4ac2d5c3f173">
](url)
**Desktop (please complete the following information):**
 - OS: Apple M2 Pro 
 - Browser  chrome, safari

**Additional context**

**Comment by tawoyinfa** [comment] 2023-10-19 20:46
@eladhaz05 the issue is a bug which is due to no permission set being assigned to the management account. Assigning a Permission set to the management account would fix it temporarily but we are working on permanent fix

**Closed** 2023-12-26 00:21 UTC
Labels: closing-soon
