### ISSUE TITLE
Intermittently unable to fetch accounts in new request

### ISSUE THREAD

**Issue by ferfecky** [aws-samples/iam-identity-center-team#292] opened 2024-08-05 11:03 UTC
**Describe the bug**

The Account drop down menu in Create request form sometimes fails to populate with values (all the user sees is the "Loading accounts" loader indefinitely). Sometimes this happens on the first page load, but the surest way to replicate is to hit the browser refresh button while on the Create request form page. The workaround is then to navigate in the menu to a different page and then navigate back to the Create request form.

Looking into the network traffic we can see the graphql onPublishPolicy subscription request gets sent, but no reply comes back.

**To Reproduce**
1. Go to 'Create request' (Elevated access request) form. 
2. Click on Account drop down menu. On first load the Account drop down usually gets populated with values normally.
3. Click on browser reload (or hit F5)
4. Click again on the Account drop down menu - in most cases this will now display a loader instead of accounts for indefinite period of time

**Expected behavior**

The account drop down menu should always populate with values.

**Screenshots**
![image](https://github.com/user-attachments/assets/8947062e-cfa7-4913-af4e-d84cca6cefb7)

![image](https://github.com/user-attachments/assets/47cf0ed8-14b6-4548-827c-3be60b5a6fea)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Tested in Firefox and Chrome

**Comment by tskibinski** [comment] 2024-09-02 09:24
Looks like a duplicate of #288

**Closed** 2024-11-08 15:06 UTC
Labels: closing-soon
